name: Node CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: hj
	run: |
	  cd ../../nodetest
      - name: pull 
        run: git pull
      - name: install
        run: npm install

      - name: restart 
        run: node index.js
