name: Node CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: pull 
        run: git pull
      - name: install
        run: npm install

      - name: restart 
        run: node index.js
